export * from './header'
export * from './hero'
export * from './top-courses'
export * from './new-courses'
export * from './speakers'
export * from './courses'
export * from './footer'
export * from './sign up'
export * from './thoughts'
export { Superiority } from './superiority'
